name: 'Feature request'
description: '새로운 기능을 제안하기 위한 양식입니다. 생성된 이슈는 Jira와 연동됩니다.'
labels: [enhancement]
title: '[FEAT] 이슈 이름을 작성해주세요'
body:
  - type: dropdown
    id: issuetype
    attributes:
      label: '🔖 이슈 유형 (Jira Issue Type)'
      description: 'Jira 상에서 사용할 이슈 타입을 선택해주세요'
      options:
        - Task
        - Sub-task
        - Story
        - Epic
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '연결할 상위 Jira 티켓 키(PRJ-00) 를 입력해주세요'
      placeholder: 'PRJ-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '영어로 브랜치명을 작성해주세요'
      placeholder: 'feature/EVER-00-New_Feature'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: '💼 작업 설명'
      description: '진행하고 싶은 기능에 대해 간단하게 설명해주세요.'
      placeholder: '예: 사용자 프로필 사진을 업로드할 수 있는 기능이 필요합니다.'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ To-do'
      description: '해당 기능을 구현하기 위한 세부 작업 목록을 작성해주세요.'
      value: |
        - [ ] todo 1
        - [ ] todo 2
        - [ ] todo 3
        - [ ] todo 4
    validations:
      required: true
